  <div id="demos-program" class="demos-program">
    <ul class="program" data-role="listview" data-filter="true" data-inset="true" data-theme="d" data-dividertheme="a" placeholder="Filter program...">
<?php
      tprog_add_header("Tuesday, August 23, 2016", "prog-tuesday");
      tprog_add_session("9:00am - 5:30pm", "Session 1 - Demo presenters onsite during coffee breaks", "", "", "prog-tuesday");
      tprog_add_item("Source Address Validation in Software Defined Networks", "http://dx.doi.org/10.1145/2934872.2960425", "B. Liu (Tsinghua University & Huawei Technologies Co. Ltd.), J. Bi (Tsinghua University), Y. Zhou (Tsinghua University)", "", "", "", "prog-tuesday");
      tprog_add_item("MACSAD: Multi-Architecture Compiler System for Abstract Dataplanes (aka Partnering P4 with ODP)", "http://dx.doi.org/10.1145/2934872.2959077", "P. Patra (University of Campinas), C. Rothenberg (University of Campinas), G. Pongr&aacute;cz (Ericsson Research)", "", "", "", "prog-tuesday");
      tprog_add_item("Capture and Replay: Reproducible Network Experiments in Mininet", "http://dx.doi.org/10.1145/2934872.2959076", "A. Fr&ouml;mmgen (TU Darmstadt), D. Stohr (TU Darmstadt), J. Fornoff (TU Darmstadt), W. Effelsberg (TU Darmstadt), A. Buchmann (TU Darmstadt)", "", "", "", "prog-tuesday");
      tprog_add_item("Towards Transiently Secure Updates in Asynchronous SDNs", "http://dx.doi.org/10.1145/2934872.2959083", "A. Shukla (TU Berlin), S. Schmid (Aalborg University), A. Feldmann (TU Berlin), A. Ludwig (TU Berlin), S. Dudycz (University of Wroclaw), A. Schuetze (TU Berlin)", "", "", "", "prog-tuesday");
      tprog_add_item("A Transparent Highway for inter-Virtual Network Function Communication with Open vSwitch", "http://dx.doi.org/10.1145/2934872.2959068", "M. V&aacute;squez (Politecnico di Torino), I. Cerrato (Politecnico di Torino), F. Risso (Politecnico di Torino), D. Verbeiren (Tessares SA, Louvain-la-Neuve)", "", "", "", "prog-tuesday");
      tprog_add_item("Cases for Including a Reference Monitor to SDN", "http://dx.doi.org/10.1145/2934872.2959066", "D. Gkounis (NEC Laboratories Europe), F. Klaedtke (NEC Laboratories Europe), R. Bifulco (NEC Laboratories Europe), G. Karame (NEC Laboratories Europe)", "", "", "", "prog-tuesday");
      tprog_add_item("High speed packet forwarding compiled from protocol independent data plane specifications", "http://dx.doi.org/10.1145/2934872.2959080", "S. Laki (E&ouml;tv&ouml;s Lor&aacute;nd University), D. Horp&aacute;csi (E&ouml;tv&ouml;s Lor&aacute;nd University), P. V&ouml;r&ouml;s (E&ouml;tv&ouml;s Lor&aacute;nd University), R. Kitlei (E&ouml;tv&ouml;s Lor&aacute;nd University), D. Lesk&oacute; (E&ouml;tv&ouml;s Lor&aacute;nd University), M. Tejfel (E&ouml;tv&ouml;s Lor&aacute;nd University)", "", "", "", "prog-tuesday");
      tprog_add_item("Roaming Edge vNFs using Glasgow Network Functions", "http://dx.doi.org/10.1145/2934872.2959067", "R. Cziva (University of Glasgow), S. Jouet (University of Glasgow), D. Pezaros (University of Glasgow)", "", "", "", "prog-tuesday");
      tprog_add_item("Modeling Native Software Components as Virtual Network Functions", "http://dx.doi.org/10.1145/2934872.2959069", "M. Baldi (Politecnico di Torino), R. Bonafiglia (Politecnico di Torino), F. Risso (Politecnico di Torino), A. Sapio (Politecnico di Torino)", "", "", "", "prog-tuesday");
      tprog_add_header("Wednesday, August 24, 2016", "prog-wednesday");
      tprog_add_session("9:00am - 5:30pm", "Session 2 - Demo presenters onsite during coffee breaks", "", "", "prog-wednesday");
      tprog_add_item("Mininet-WiFi: A Platform for Hybrid Physical-Virtual Software-Defined Wireless Networking Research", "http://dx.doi.org/10.1145/2934872.2959070", "R. Fontes (University of Campinas), C. Rothenberg (University of Campinas), R. Fontes (University of Campinas)", "", "", "", "prog-wednesday");
      tprog_add_item("Multi-Domain Orchestration across RAN and Transport for 5G", "http://dx.doi.org/10.1145/2934872.2959073", "A. Rostami (Ericsson Research), P. &Ouml;hl&eacute;n (Ericsson Research), M. Santos (Ericsson Research), A. Vidal (Ericsson Research)", "", "", "", "prog-wednesday");
      tprog_add_item("Enabling Backscatter Communication among Commodity WiFi Radios", "http://dx.doi.org/10.1145/2934872.2959072", "P. Zhang (Stanford University), D. Bharadia (MIT), K. Joshi (Stanford University), S. Katti (Stanford University), P. Zhang (University of Massachusetts Amherst)", "", "", "", "prog-wednesday");
      tprog_add_item("Off-the-Shelf Software-defined Wi-Fi Networks", "http://dx.doi.org/10.1145/2934872.2959071", "S. H&auml;t&ouml;nen (University of Helsinki), P. Savolainen (Helsinki Institute for Information Technology HIIT), A. Rao (University of Helsinki), H. Flinck (Nokia Bell Labs), S. Tarkoma (University of Helsinki)", "", "", "", "prog-wednesday");
      tprog_add_item("ARTEMIS: Real-Time Detection and Automatic Mitigation for BGP Prefix Hijacking", "http://dx.doi.org/10.1145/2934872.2959078", "G. Chaviaras (FORTH), P. Gigis (FORTH), P. Sermpezis (FORTH), X. Dimitropoulos (FORTH)", "", "", "", "prog-wednesday");
      tprog_add_item("EasyApp: A Cross-platform Mobile Applications Development Environment Based on OSGi", "http://dx.doi.org/10.1145/2934872.2959074", "Z. Wang (Beijing University of Posts and Telecommunications), B. Cheng (Beijing University of Posts and Telecommunications), Z. Zhai (Beijing University of Posts and Telecommunications), Y. Jin (Beijing University of Posts and Telecommunications), Y. Feng (Beijing University of Posts and Telecommunications), J. Chen (Beijing University of Posts and Telecommunications)", "", "", "", "prog-wednesday");
      tprog_add_item("A 60Gbps DPI Prototype based on Memory-Centric FPGA", "http://dx.doi.org/10.1145/2934872.2959079", "J. Su (National Laboratory for Parallel and Distributed Processing / National University of Defense Technology), S. Chen (National University of Defense Technology), B. Han (National University of Defense Technology),C. Xu (National University of Defense Technology), X. Wang (National University of Defense Technology)", "", "", "", "prog-wednesday");
      tprog_add_item("Application Driven Network: providing On-Demand Services for Applications", "http://dx.doi.org/10.1145/2934872.2959075", "Y. Wang (Huawei Future Network Theory Lab), D. Lin (Huawei Future Network Theory Lab), C. Li (Huawei Future Network Theory Lab), J. Zhang (Huawei Wireless Technology Lab), P. Liu (Huawei Wireless Technology Lab), C. Hu (Xi'an Jiaotong University), G. Zhang (Huawei Future Network Theory Lab)", "", "", "", "prog-wednesday");
      tprog_add_item("Fibbing in action: On-demand load-balancing for better video delivery", "http://dx.doi.org/10.1145/2934872.2959084", "O. Tilmans (Universit&eacute; Catholique de Louvain), S. Vissicchio (Universit&eacute; Catholique de Louvain), L. Vanbever (ETH Z&uuml;rich), J. Rexford (Princeton University)", "", "", "", "prog-wednesday");
?>
    </ul>
  </div>
