  <div id="maintrackposters-program" class="maintrackposters-program">
    <ul class="program" data-role="listview" data-filter="true" data-inset="true" data-theme="d" data-dividertheme="a" placeholder="Filter program...">
<?php
      tprog_add_header("Thursday, August 25, 2016", "prog-thursday");
      tprog_add_session("9:00am - 5:30pm", "Posters/Demos from Main Track - Presenters onsite during coffee breaks", "", "", "prog-thursday");
      tprog_add_item("Don't Mind the Gap: Bridging Network-wide Objectives and Device-level Configurations", "", "R. Beckett (Princeton University), R. Mahajan (Microsoft Research), J. Padhye (Microsoft Research), T. Millstein (University of California, Los Angeles), D. Walker (Princeton University)", "", "", "", "prog-thursday");
      tprog_add_item("Top-down Network Management on a Massive Scale", "", "E. Sung (Facebook), X. Tie (Facebook), S. Wong (Facebook), H. Zeng (Facebook)", "", "", "", "prog-thursday");
      tprog_add_item("Enabling Practical Backscatter Communication for On-body Sensors", "", "P. Zhang(University of Massachusetts Amherst), M. Rostami(University of Massachusetts Amherst), P. Hu(University of Massachusetts Amherst), D. Ganesan (University of Massachusetts Amherst)", "", "", "", "prog-thursday");
      tprog_add_item("Hypervisor-based Algorithmic Virtualization of TCP Congestion Control", "", "B. Cronkite-Ratcliff (Stanford), A. Bergman (Technion), S. Vargaftik (Technion), M. Ravi (VMware), N. McKeown (Stanford), I. Abraham (VMware), I. Keslassy (Technion / VMware)", "", "", "", "prog-thursday");
      tprog_add_item("Globally Synchronized Time via Datacenter Networks", "", "K. S. Lee (Cornell University), H. Wang (Cornell University), V. Shrivastav (Cornell University), H. Weatherspoon (Cornell University)", "", "", "", "prog-thursday");
      tprog_add_item("Braidio: An Integrated Active-Passive Radio for Mobile Devices with Asymmetric Energy Budgets", "", "Pan Hu, Pengyu Zhang, Mohammad Rostami, and Deepak Ganesan (University of Massachusetts Amherst)", "", "", "", "prog-thursday");
      tprog_add_item("ClickNP: Highly Flexible and High-performance Network Processing with Reconfigurable Hardware", "", "B. Li (USTC / Microsoft Research), K. Tan (Microsoft Research), L. Luo (Microsoft), Y. Peng (SJTU / Microsoft Research), R. Luo (USTC / Microsoft Research), N. Xu (Microsoft Research), Y. Xiong (Microsoft Research), P. Cheng (Microsoft Research)", "", "", "", "prog-thursday");
      tprog_add_item("PISCES: A Programmable, Protocol-Independent Software Switch", "", "M. Shahbaz (Princeton University), S. Choi (Stanford University), B. Pfaff (VMware), C. Kim (Barefoot Networks), N. Feamster (Princeton University), N. McKeown (Stanford University), J. Rexford (Princeton University)", "", "", "", "prog-thursday");
      tprog_add_item("Dataplane Specialization for High-performance OpenFlow Software Switching", "", "L. Moln&aacute;r (Ericsson Research, Hungary), G. Pongr&aacute;cz (Ericsson Research, Hungary), G. Enyedi (Ericsson Research, Hungary), Z. Kis (Ericsson Research, Hungary), L. Csikor (Budapest University of Technology and Economics), F. Juh&aacute;sz (Budapest University of Technology and Economics), A. K&ouml;r&ouml;si (Budapest University of Technology and Economics), G. R&eacute;tv&aacute;ri (Budapest University of Technology and Economics)", "", "", "", "prog-thursday");
      tprog_add_item("One Sketch to Rule Them All: Rethinking Network Flow Monitoring with UnivMon", "", "Z. Liu (Johns Hopkins University), A. Manousis (Carnegie Mellon University), G. Vorsanger (Johns Hopkins University), V. Sekar (Carnegie Mellon University), V. Braverman (Johns Hopkins University)", "", "", "", "prog-thursday");
      tprog_add_item("Neutral Net Neutrality", "", "Y. Yiakoumis (Stanford University), S. Katti (Stanford University), N. McKeown (Stanford University)", "", "", "", "prog-thursday");
?>
    </ul>
  </div>
