  <div id="posters-program" class="posters-program">
    <ul class="program" data-role="listview" data-filter="true" data-inset="true" data-theme="d" data-dividertheme="a" placeholder="Filter program...">
<?php
      tprog_add_header("Tuesday, August 23, 2016", "prog-tuesday");
      tprog_add_session("9:00am - 5:30pm", "Session 1", "", "", "prog-tuesday");
      tprog_add_item("PieBridge: A Cross-DR scale Large Data Transmission Scheduling System", "", "Y. Zhang&nbsp;(Tsinghua University), K. Xu&nbsp;(Tsinghua University), G. Yao&nbsp;(Baidu), M. Zhang&nbsp;(Baidu), X. Nie&nbsp;(Tsinghua University)", "", "", "", "prog-tuesday");
      tprog_add_item("A Longitudinal Analysis of .i2p Leakage in the Public DNS Infrastructure", "", "S. Jeong (Korea University), A. Kang (SUNY Buffalo), J. Kim (Chung-Ang University), H. Kim (Korea University), A. Mohaisen (SUNY Buffalo)", "", "", "", "prog-tuesday");
      tprog_add_item("Best Effort Task Scheduling for Data Parallel Jobs", "", "Z. Li (National University of Defense Technology), Y. Zhang (National University of Defense Technology), Y. Zhao (National University of Defense Technology), Y. Peng (National University of Defense Technology), D. Li (National University of Defense Technology)", "", "", "", "prog-tuesday");
      tprog_add_item("Efficient Remapping of Internet Routing Events", "", "E. Fazzion (Universidade Federal de Minas Gerais), &Iacute;. Cunha (Universidade Federal de Minas Gerais), D. Guedes (Universidade Federal de Minas Gerais), W. Meira Jr. (Universidade Federal de Minas Gerais), R. Teixeira (Inria), D. Veitch (University of Technology Sydney), C. Diot (Safran)", "", "", "", "prog-tuesday");
      tprog_add_item("Privacy-Aware Infrastructure for Managing Personal Data", "", "Y. Amar (Queen Mary University of London), H. Haddadi (Queen Mary University of London), R. Mortier (University of Cambridge)", "", "", "", "prog-tuesday");
      tprog_add_item("Performance Evaluation of Locator/Identifier Separation Protocol through RIPE Atlas", "", "Y. Li (Telecom ParisTech), L. Iannone (Telecom ParisTech)", "", "", "", "prog-tuesday");
      tprog_add_item("TafLoc: Time-adaptive and Fine-grained Device-free Localization with Little Cost", "", "L. Chang (Northwest University), J. Xiong (Singapore Management University), X. Chen (Northwest University), J. Wang (Northwest University), J. Hu (Northwest University), D. Fang (Northwest University), W. Wang (Northwest University), L. Chang (Northwest University)", "", "", "", "prog-tuesday");
      tprog_add_item("A First Look into Transnational Routing Detours", "", "A. Edmundson (Princeton University), R. Ensafi (Princeton University), N. Feamster (Princeton University), J. Rexford (Princeton University)", "", "", "", "prog-tuesday");
      tprog_add_item("PathCache: A Path Prediction Toolkit", "", "R. Singh (Stony Brook University), P. Gill (Stony Brook University)", "", "", "", "prog-tuesday");
      tprog_add_item("Application-specific Acceleration Framework for Mobile Applications", "", "B. Choi (KAIST), J. Kim (KAIST), D. Han (KAIST)", "", "", "", "prog-tuesday");
      tprog_add_header("Wednesday, August 24, 2016", "prog-wednesday");
      tprog_add_session("9:00am - 5:30pm", "Session 2", "", "", "prog-wednesday");
      tprog_add_item("Named Data Networking Based Smart Home Lighting", "", "U. De Silva (Asian Institute of Technology), A. Lertsinsrubtavee (University of Cambridge), A. Sathiaseelan (University of Cambridge), K. Kanchanasut (Asian Institute of Technology)", "", "", "", "prog-wednesday");
      tprog_add_item("Achieving Consistent SDN Control With Declarative Applications", "", "W. Wang (McGill Unversity), C. Liu (Logistic Information Center), J. Su (National University Of Defense Technology), W. He (McGill Unversity)", "", "", "", "prog-wednesday");
      tprog_add_item("Modular SDN Compiler Design with Intermediate Representation", "", "H. Li (Xi'an Jiaotong University), C. Hu (Xi'an Jiaotong University), P. Zhang (Xi'an Jiaotong University), L. Xie (Xi'an Jiaotong University)", "", "", "", "prog-wednesday");
      tprog_add_item("SLA-NFV: an SLA-aware High Performance Framework for Network Function Virtualization", "", "C. Sun (Tsinghua University), J. Bi (Tsinghua University), Z. Zheng (Tsinghua University), H. Hu (Clemson University)", "", "", "", "prog-wednesday");
      tprog_add_item("Conan: Content-aware Access Network Flow Scheduling to Improve QoE of Home Users", "", "H. Yang (Nanjing University), X. Wang (Nanjing University), C. Nguyen (Nanjing University), S. Lu (Nanjing University)", "", "", "", "prog-wednesday");
      tprog_add_item("Building Application-Aware Network Environments using SDN for Optimizing Hadoop Applications", "", "S. Zhao (University of Missouri - Kansas City), A. Sydney (Raytheon BBN Technologies), D. Medhi (University of Missouri - Kansas City), S. Zhao (University of Missouri - Kansas City)", "", "", "", "prog-wednesday");
      tprog_add_item("Horse: towards an SDN traffic dynamics simulator for large scale networks", "", "E. Fernandes (Queen Mary, University of London), G. Antichi (University of Cambridge), I. Castro (Queen Mary, University of London), S. Uhlig (Queen Mary, University of London)", "", "", "", "prog-wednesday");
      tprog_add_item("Rethinking the Design of OpenFlow Switch Counters", "", "J. Yang (Xian Jiaotong Unviersity), C. Hu (Xian Jiaotong Unviersity), P. Zheng (Xian Jiaotong Unviersity), R. Wang (Xian Jiaotong Unviersity), P. Zhang (Xian Jiaotong Unviersity), X. Guan (Xian Jiaotong University / Tsinghua University)", "", "", "", "prog-wednesday");
      tprog_add_item("Taming the Flow Table Overflow in OpenFlow Switch", "", "S. Qiao (Xi&rsquo;an Jiaotong University), C. Hu (Xi&rsquo;an Jiaotong University), X. Guan (Xi&rsquo;an Jiaotong University), J. Zou (Xi&rsquo;an Jiaotong University)", "", "", "", "prog-wednesday");
      tprog_add_item("Magellan: Generating Multi-Table Datapath from Datapath Oblivious Algorithmic SDN Policies", "", "A. Voellmy (Yale University), S. Chen (Tongji University), X. Wang (Tongji University), Y. Yang (Yale University)", "", "", "", "prog-wednesday");
      tprog_add_item("FAST: A Simple Programming Abstraction for Complex State-Dependent SDN Programming", "", "K. Gao (Tsinghua University), C. Gu (Tongji University), Q. Xiang (Tongji/Yale University), Y. Yang (Tongji/Yale University), J. Bi (Tsinghua University), Q. Xiang (Yale University)", "", "", "", "prog-wednesday");
?>
    </ul>
  </div>
