  <div id="sigcomm-program" class="sigcomm-program">
    <ul class="program" data-role="listview" data-filter="true" data-inset="true" data-theme="d" data-dividertheme="a" placeholder="Filter program...">
<?php
      tprog_add_header("Monday, August 22, 2016", "prog-monday");
      tprog_add_session("5:30pm - 6:45pm", "Topic Preview 1 - SDN, NFV, DCN, TCP, Scheduling", "", "", "prog-monday");
      tprog_add_item("Topic Preview 1 - SDN, NFV, DCN, TCP, Scheduling", "", "Schedule may change. Please check back for final schedule and speaker details.", "", "", "", "prog-monday");
      tprog_add_extra("", "Welcome Reception", "prog-monday");
      tprog_add_item("Welcome Reception", "", "The Welcome Reception will take place at the Oceania Convention Center. Drinks and hors d'oeuvre will be served. Please visit the <a href=socialevents.php>Social Events</a> page for further information.", "", "", "", "prog-monday");
      tprog_add_extra("", "N2Women Dinner", "prog-monday");
      tprog_add_item("N2Women Dinner", "", "Participation in this event is by invitation only. If you have any inquiries or would like to receive an invitation, please contact the N2Women chairs.", "", "", "", "prog-monday");
      tprog_add_extra("", "Award Dinner", "prog-monday");
      tprog_add_item("Award Dinner", "", "Participation in this event is by invitation only.", "", "", "", "prog-monday");
      tprog_add_header("Tuesday, August 23, 2016", "prog-tuesday");
      tprog_add_session("8:45am - 10:30am", "Opening", "", "", "prog-tuesday");
      tprog_add_keynote("Keynote: Networking Research, Education, Mentoring and Service: Ten Insights", "Jim Kurose (University of Massachusetts, Amherst), 2016 ACM SIGCOMM Lifetime Achievement Award Recipient", "To be announced soon.", "Jim Kurose received a B.A. degree in physics from Wesleyan University and his Ph.D. degree in computer science from Columbia University. He is currently Distinguished University Professor in the College of Information and Computer Sciences at the University of Massachusetts Amherst. He has been a Visiting Scientist at IBM Research, INRIA, Institut EURECOM , the University of Paris, the Laboratory for Information, Network and Communication Sciences, and Technicolor Research Labs.<br/>
<br/>
His research interests include network protocols and architecture, network measurement, sensor networks, and multimedia communication. Dr. Kurose has served as Editor-in- Chief of the IEEE Transactions on Communications and was the founding Editor-in- Chief of the IEEE/ACM Transactions on Networking. He has been Technical Program Co-Chair for the IEEE Infocom, ACM SIGCOMM, ACM SIGMETRICS, and ACM Internet Measurement conferences. He has won several conference best paper awards and received the IEEE Infocom Achievement Award and the ACM Sigcomm Test of Time Award.<br/>
<br/>
He has received a number of awards for his teaching including outstanding teacher awards from the National Technological University, the UMass College of Natural Science and Mathematics, and the Northeast Association of Graduate Schools, and the IEEE Taylor Booth Education Medal. He has recently served on the Board of Directors of the Computing Research Association, and on the scientific advisory boards of IMDEA Networks in Madrid and the Laboratory for Information, Network and Communication Sciences (LINCS) in Paris. With Keith Ross, he is the co-author of the textbook, Computer Networking, a top down approach (7th edition), published by Addison-Wesley/Pearson. He is a Fellow of the ACM and the IEEE.<br/>
<br/>
Since January 2015, he is serving as an Assistant Director of the US National Science Foundation, where he leads the Directorate for the Computer and Information Science and Engineering (CISE) in its mission to fundamental research in computer and information science and engineering and transformative advances in cyberinfrastructure. Dr. Kurose oversees the CISE budget of more than $900 million. He also serves as co-chair of the Networking and Information Technology Research and Development (NITRD) Subcommittee of the National Science and Technology Council Committee on Technology, helping coordinate the activities of 17 government agencies.", "images/program/sigcomm/jim-kurose.jpg", "", "prog-tuesday");

      tprog_add_session("10:30am - 11:00am", "Coffee Break", "", "", "prog-tuesday");
      tprog_add_session("11:00am - 12:40pm", "Session 1 - SDN & NFV", "", "", "prog-tuesday");
      tprog_add_item("ClickNP: Highly Flexible and High Performance Network Processing with Reconfigurable Hardware", "http://dx.doi.org/10.1145/2934872.2934897", "Bojie Li (USTC / Microsoft Research), Kun Tan (Microsoft Research), Layong (Larry) Luo (Microsoft), Yanqing Peng (SJTU / Microsoft Research), Renqian Luo (USTC / Microsoft Research), Ningyi Xu (Microsoft Research), Yongqiang Xiong (Microsoft Research), Peng Cheng (Microsoft Research), Enhong Chen (USTC)", "", "", "", "prog-tuesday");
      tprog_add_item("Packet Transactions: High-Level Programming for Line-Rate Switches", "http://dx.doi.org/10.1145/2934872.2934900", "Anirudh Sivaraman (MIT CSAIL), Alvin Cheung (University of Washington, Seattle), Mihai Budiu (VMWare Research), Changhoon Kim (Barefoot Networks), Mohammad Alizadeh (MIT CSAIL), Hari Balakrishnan (MIT CSAIL), George Varghese (Microsoft Research), Nick McKeown (Stanford University), Steve Licking (Barefoot Networks)", "", "", "", "prog-tuesday");
      tprog_add_item("SNAP: Stateful Network-Wide Abstractions for Packet Processing", "http://dx.doi.org/10.1145/2934872.2934892", "Mina Tahmasbi Arashloo (Princeton University), Yaron Koral (Princeton University), Michael Greenberg (Pomona College), Jennifer Rexford (Princeton University), David Walker (Princeton University)", "", "", "", "prog-tuesday");
      tprog_add_item("Programmable Packet Scheduling at Line Rate", "http://dx.doi.org/10.1145/2934872.2934899", "Anirudh Sivaraman (MIT CSAIL), Suvinay Subramanian (MIT CSAIL), Mohammad Alizadeh (MIT CSAIL), Sharad Chole (Cisco Systems), Shang-Tse Chuang (Cisco Systems), Anurag Agrawal (Barefoot Networks), Hari Balakrishnan (MIT CSAIL), Tom Edsall (Cisco Systems), Sachin Katti (Stanford University), Nick McKeown (Stanford University)", "", "", "", "prog-tuesday");
      tprog_add_session("12:40pm - 2:00pm", "Lunch Break", "", "", "prog-tuesday");
      tprog_add_session("2:00pm - 3:15pm", "Session 2 - Wide Area Networks", "", "", "prog-tuesday");
      tprog_add_item("Evolve or Die: High-Availability Design Principles Drawn from Google's Network Infrastructure", "http://dx.doi.org/10.1145/2934872.2934891", "Ramesh Govindan (Google / USC), Ina Minei (Google), Mahesh Kallahalla (Google), Bikash Koley (Google), Amin Vahdat (Google)", "", "", "", "prog-tuesday");
      tprog_add_item("Dynamic Pricing and Traffic Engineering for Timely Inter-Datacenter Transfers", "http://dx.doi.org/10.1145/2934872.2934893", "Virajith Jalaparti (Microsoft), Ivan Bliznets (St. Petersburg Academic University), Srikanth Kandula (Microsoft), Brendan Lucier (Microsoft), Ishai Menache (Microsoft)", "", "", "", "prog-tuesday");
      tprog_add_item("Optimizing Bulk Transfers with Software-Defined Optical WAN", "http://dx.doi.org/10.1145/2934872.2934904", "Xin Jin (Princeton University), Yiran Li (Tsinghua University), Da Wei (Tsinghua University), Siming Li (Stony Brook University), Jie Gao (Stony Brook University), Lei Xu (Sodero Networks), Guangzhi Li (AT&T Labs), Wei Xu (Tsinghua University), Jennifer Rexford (Princeton University)", "", "", "", "prog-tuesday");
      tprog_add_session("3:15pm - 4:15pm", "Coffee Break", "", "", "prog-tuesday");
      tprog_add_session("4:15pm - 5:30pm", "Session 3 - Monitoring and Diagnostics", "", "", "prog-tuesday");
      tprog_add_item("One Sketch to Rule Them All: Rethinking Network Flow Monitoring with UnivMon", "http://dx.doi.org/10.1145/2934872.2934906", "Zaoxing Liu (Johns Hopkins University), Antonis Manousis (Carnegie Mellon University), Gregory Vorsanger (Johns Hopkins University), Vyas Sekar (Carnegie Mellon University), Vladimir Braverman (Johns Hopkins University)", "", "", "", "prog-tuesday");
      tprog_add_item("The Good, the Bad, and the Differences: Better Network Diagnostics with Differential Provenance", "http://dx.doi.org/10.1145/2934872.2934910", "Ang Chen (University of Pennsylvania), Yang Wu (University of Pennsylvania), Andreas Haeberlen (University of Pennsylvania), Wenchao Zhou (Georgetown University), Boon Thau Loo (University of Pennsylvania)", "", "", "", "prog-tuesday");
      tprog_add_item("Trumpet: Timely and Precise Triggers in Data Centers", "http://dx.doi.org/10.1145/2934872.2934879", "Masoud Moshref (University of Southern California), Minlan Yu (University of Southern California), Ramesh Govindan (University of Southern California), Amin Vahdat (Google)", "", "", "", "prog-tuesday");
      tprog_add_extra("7:00pm - 11:30pm", "Conference Banquet", "prog-tuesday");
      tprog_add_item("Conference Banquet", "", "The Conference Banquet will take place at the Slaviero Essential Florian&oacute;polis Ingleses. Please visit the <a href=socialevents.php>Social Events</a> page for further information.", "", "", "", "prog-tuesday");
      tprog_add_header("Wednesday, August 24, 2016", "prog-wednesday");
      tprog_add_session("8:30am - 10:10am", "Session 4 - Scheduling", "", "", "prog-wednesday");
      tprog_add_item("2DFQ: Two-Dimensional Fair Queueing for Multi-Tenant Cloud Services", "http://dx.doi.org/10.1145/2934872.2934878", "Jonathan Mace (Brown University), Peter Bodik (Microsoft), Madanlal Musuvathi (Microsoft), Rodrigo Fonseca (Brown University), Krishnan Varadarajan (Microsoft)", "", "", "", "prog-wednesday");
      tprog_add_item("CODA: Toward Automatically Identifying and Scheduling Coflows in the Dark", "http://dx.doi.org/10.1145/2934872.2934880", "Hong Zhang (Hong Kong University of Science and Technology), Li Chen (Hong Kong University of Science and Technology), Bairen Yi (Hong Kong University of Science and Technology), Kai Chen (Hong Kong University of Science and Technology), Mosharaf Chowdhury (University of Michigan), Yanhui Geng (Huawei Noah's Ark Lab)", "", "", "", "prog-wednesday");
      tprog_add_item("Scheduling Mix-flows in Commodity Datacenters with Karuna", "http://dx.doi.org/10.1145/2934872.2934888", "Li Chen (Hong Kong University of Science and Technology), Kai Chen (Hong Kong University of Science and Technology), Wei Bai (Hong Kong University of Science and Technology), Mohammad Alizadeh (MIT)", "", "", "", "prog-wednesday");
      tprog_add_item("NUMFabric: Fast and Flexible Bandwidth Allocation in Datacenters", "http://dx.doi.org/10.1145/2934872.2934890", "Kanthi Nagaraj (Stanford University), Dinesh Bharadia (Stanford University), Hongzi Mao (M.I.T), Sandeep Chinchali (Stanford University), Mohammad Alizadeh (M.I.T.), Sachin Katti (Stanford University)", "", "", "", "prog-wednesday");
      tprog_add_session("10:10am - 10:40am", "Coffee Break", "", "", "prog-wednesday");
      tprog_add_session("10:40am - 12:20pm", "Session 5 - Datacenters", "", "", "prog-wednesday");
      tprog_add_item("RDMA over Commodity Ethernet at Scale", "http://dx.doi.org/10.1145/2934872.2934908", "Chuanxiong Guo (Microsoft Research), Haitao Wu (Microsoft), Zhong Deng (Microsoft), Gaurav Soni (Microsoft), Jianxi Ye (Microsoft), Jitu Padhye (Microsoft Research), Marina Lipshteyn (Microsoft)", "", "", "", "prog-wednesday");
      tprog_add_item("ProjecToR: Agile Reconfigurable Data Center Interconnect", "http://dx.doi.org/10.1145/2934872.2934911", "Monia Ghobadi (Microsoft Research), Ratul Mahajan (Microsoft Research), Amar Phanishayee (Microsoft Research), Nikhil Devanur (Microsoft Research), Janardhan Kulkarni (Microsoft Research), Gireeja Ranade (Microsoft Research), Pierre-Alexandre Blanche (University of Arizona), Houman Rastegarfar (University of Arizona), Madeleine Glick (University of Arizona), Daniel Kilper (University of Arizona)", "", "", "", "prog-wednesday");
      tprog_add_item("Virtualized Congestion Control", "http://dx.doi.org/10.1145/2934872.2934889", "Bryce Cronkite-Ratcliff (VMware / Stanford), Aran Bergman (Technion), Shay Vargaftik (Technion), Madhusudhan Ravi (VMware), Nick McKeown (Stanford), Ittai Abraham (VMware), Isaac Keslassy (VMware / Stanford / Technion)", "", "", "", "prog-wednesday");
      tprog_add_item("AC/DC TCP: Virtual Congestion Control Enforcement for Datacenter Networks", "http://dx.doi.org/10.1145/2934872.2934903", "Keqiang He (University of Wisconsin-Madison), Eric Rozner (IBM Research), Kanak Agarwal (IBM), Yu (Jason) Gu (IBM), Wes Felter (IBM Research), John Carter (IBM), Aditya Akella (University of Wisconsin-Madison)", "", "", "", "prog-wednesday");
      tprog_add_session("12:20pm - 1:30pm", "Lunch Break", "", "", "prog-wednesday");
      tprog_add_session("12:20pm - 1:30pm", "Topic Preview 2 - Wireless, Verification, Censorship/Choice", "", "", "prog-wednesday");
      tprog_add_item("Topic Preview 2 - Wireless, Verification, Censorship/Choice", "", "Schedule may change. Please check back for final schedule and speaker details.", "", "", "", "prog-wednesday");
      tprog_add_session("1:30pm - 2:45pm", "Session 6 - Networked Applications", "", "", "prog-wednesday");
      tprog_add_item("WebPerf: Evaluating What-If Scenarios for Cloud-hosted Web Applications", "http://dx.doi.org/10.1145/2934872.2934882", "Yurong Jiang (University of Southern California), Lenin Ravindranath (Microsoft Research), Suman Nath (Microsoft Research), Ramesh Govindan (University of Southern California)", "", "", "", "prog-wednesday");
      tprog_add_item("CS2P: Improving Video Bitrate Selection and Adaptation with Data-Driven Throughput Prediction", "http://dx.doi.org/10.1145/2934872.2934898", "Yi Sun (ICT/CAS), Xiaoqi Yin (CMU), Junchen Jiang (CMU), Vyas Sekar (CMU), Fuyuan Lin (ICT/CAS), Nanshu Wang (ICT/CAS), Tao Liu (iQIYI), Bruno Sinopoli (CMU)", "", "", "", "prog-wednesday");
      tprog_add_item("Via: Improving Internet Telephony Call Quality Using Predictive Relay Selection", "http://dx.doi.org/10.1145/2934872.2934907", "Junchen Jiang (Microsoft Research / CMU), Rajdeep Das (Microsoft Research), Ganesh Ananthanarayanan (Microsoft Research), Philip A. Chou (Microsoft Research), Venkata Padmanabhan (Microsoft Research), Vyas Sekar (CMU), Esbjorn Dominique (Microsoft), Marcin Goliszewski (Microsoft), Dalibor Kukoleca (Microsoft), Renat Vafin (Microsoft), Hui Zhang (CMU)", "", "", "", "prog-wednesday");
      tprog_add_session("2:45pm - 3:45pm", "Coffee Break", "", "", "prog-wednesday");
      tprog_add_session("3:45pm - 5:25pm", "Session 7 - Verification", "", "", "prog-wednesday");
      tprog_add_item("Fast Control Plane Analysis Using an Abstract Representation", "http://dx.doi.org/10.1145/2934872.2934876", "Aaron Gember-Jacobson (University of Wisconsin-Madison), Raajay Viswanathan (University of Wisconsin-Madison), Aditya Akella (University of Wisconsin-Madison), Ratul Mahajan (Microsoft Research)", "", "", "", "prog-wednesday");
      tprog_add_item("Symnet: scalable symbolic execution for modern networks", "http://dx.doi.org/10.1145/2934872.2934881", "Radu Stoenescu (University Politehnica of Bucharest), Matei Popovici (University Politehnica of Bucharest), Lorina Negreanu (University Politehnica of Bucharest), Costin Raiciu (University Politehnica of Bucharest)", "", "", "", "prog-wednesday");
      tprog_add_item("Don't Mind the Gap: Bridging Network-wide Objectives and Device-level Configurations", "http://dx.doi.org/10.1145/2934872.2934909", "Ryan Beckett (Princeton University), Ratul Mahajan (Microsoft), Todd Millstein (University of California, Los Angeles), Jitendra Padhye (Microsoft), David Walker (Princeton University)", "", "", "", "prog-wednesday");
      tprog_add_item("Jumpstarting BGP Security with Path-End Validation", "http://dx.doi.org/10.1145/2934872.2934883", "Avichai Cohen (Hebrew University), Yossi Gilad (Boston University and MIT), Amir Herzberg (Bar Ilan University), Michael Schapira (Hebrew University)", "", "", "", "prog-wednesday");
      tprog_add_session("5:30pm - 6:30pm", "Community Feedback", "", "", "prog-wednesday");
      tprog_add_item("Community Feedback", "", "", "", "", "", "prog-wednesday");
      tprog_add_extra("7:30pm - 10:00pm", "Student Dinner", "prog-wednesday");
      tprog_add_item("Student Dinner", "", "The SIGCOMM 2016 Student Dinner will take place at Ataliba Churrascarias Florian&oacute;polis. Please visit the <a href=socialevents.php>Social Events</a> page for further information.", "", "", "", "prog-wednesday");
      tprog_add_header("Thursday, August 25, 2016", "prog-thursday");
      tprog_add_session("8:30am - 10:35am", "Session 8 - Wireless", "", "", "prog-thursday");
      tprog_add_item("Inter-Technology Backscatter: Towards Internet Connectivity for Implanted Devices", "http://dx.doi.org/10.1145/2934872.2934894", "Vikram Iyer (University of Washington), Vamsi Talla (University of Washington), Bryce Kellogg (University of Washington), Shyamnath Gollakota (University of Washington), Joshua Smith (University of Washington)", "", "", "", "prog-thursday");
      tprog_add_item("Enabling Practical Backscatter Communication for On-body Sensors", "http://dx.doi.org/10.1145/2934872.2934901", "Pengyu Zhang (University of Massachusetts Amherst), Mohammad Rostami (University of Massachusetts Amherst), Pan Hu (University of Massachusetts Amherst), Deepak Ganesan (University of Massachusetts Amherst)", "", "", "", "prog-thursday");
      tprog_add_item("Braidio: An Integrated Active-Passive Radio for Mobile Devices with Asymmetric Energy Budgets", "http://dx.doi.org/10.1145/2934872.2934902", "Pan Hu (University of Massachusetts Amherst), Pengyu Zhang (University of Massachusetts Amherst), Mohammad Rostami (University of Massachusetts Amherst), Deepak Ganesan (University of Massachusetts Amherst)", "", "", "", "prog-thursday");
      tprog_add_item("Eliminating Channel Feedback in Next-Generation Cellular Networks", "http://dx.doi.org/10.1145/2934872.2934895", "Deepak Vasisht (MIT), Swarun Kumar (CMU), Hariharan Rahul (MIT), Dina Katabi (MIT)", "", "", "", "prog-thursday");
      tprog_add_item("Real-time Distributed MIMO Systems", "http://dx.doi.org/10.1145/2934872.2934905", "Ezzeldin Hamed (Massachusetts Institute of Technology), Hariharan Rahul (Massachusetts Institute of Technology), Mohammed A. Abdelghany (Massachusetts Institute of Technology), Dina Katabi (Massachusetts Institute of Technology)", "", "", "", "prog-thursday");
      tprog_add_session("10:35am - 11:05am", "Coffee Break", "", "", "prog-thursday");
      tprog_add_session("11:05am - 12:20pm", "Session 9 - Datacenters", "", "", "prog-thursday");
      tprog_add_item("Robotron: Top-down Network Management at Facebook Scale", "http://dx.doi.org/10.1145/2934872.2934874", "Yu-Wei Eric Sung (Facebook), Xiaozheng Tie (Facebook), Starsky H.Y. Wong (Facebook), Hongyi Zeng (Facebook)", "", "", "", "prog-thursday");
      tprog_add_item("Taking the Blame Game out of Data Centers Operations with NetPoirot", "http://dx.doi.org/10.1145/2934872.2934884", "Behnaz Arzani (University of Pennsylvania), Selim Ciraci (Microsoft), Boon Thau Loo (University of Pennsylvania), Assaf Schuster (Technion - Israel Institute of Technology), Geoff Outhred (Microsoft)", "", "", "", "prog-thursday");
      tprog_add_item("Globally Synchronized Time via Datacenter Networks", "http://dx.doi.org/10.1145/2934872.2934885", "Ki Suh Lee (Cornell University), Han Wang (Cornell University), Vishal Shrivastav (Cornell University), Hakim Weatherspoon (Cornell University)", "", "", "", "prog-thursday");
      tprog_add_session("12:20pm - 1:30pm", "Lunch Break", "", "", "prog-thursday");
      tprog_add_session("1:30pm - 2:45pm", "Session 10 - Censorship and Choice", "", "", "prog-thursday");
      tprog_add_item("An Internet-Wide Analysis of Traffic Policing", "http://dx.doi.org/10.1145/2934872.2934873", "Tobias Flach (University of Southern California / Google), Pavlos Papageorge (Google), Andreas Terzis (Google), Luis Pedrosa (University of Southern California), Yuchung Cheng (Google), Tayeb Karim (Google), Ethan Katz-Bassett (University of Southern California), Ramesh Govindan (University of Southern California / Google)", "", "", "", "prog-thursday");
      tprog_add_item("Neutral Net Neutrality", "http://dx.doi.org/10.1145/2934872.2934896", "Yiannis Yiakoumis (Stanford University), Sachin Katti (Stanford University), Nick McKeown (Stanford University)", "", "", "", "prog-thursday");
      tprog_add_item("The Deforestation of L2", "http://dx.doi.org/10.1145/2934872.2934877", "James McCauley (UC Berkeley / ICSI), Mingjie Zhao (UESTC / ICSI), Ethan J. Jackson (UC Berkeley), Barath Raghavan (ICSI), Sylvia Ratnasamy (UC Berkeley / ICSI), Scott Shenker (UC Berkeley / ICSI)", "", "", "", "prog-thursday");
      tprog_add_session("2:45pm - 3:45pm", "Coffee Break", "", "", "prog-thursday");
      tprog_add_session("3:45pm - 5:00pm", "Session 11 - SDN & NFV", "", "", "prog-thursday");
      tprog_add_item("OpenBox: A Software-Defined Framework for Developing, Deploying, and Managing Network Functions", "http://dx.doi.org/10.1145/2934872.2934875", "Anat Bremler-Barr (The Interdisciplinary Center, Herzliya), Yotam Harchol (The Hebrew University of Jerusalem), David Hay (The Hebrew University of Jerusalem)", "", "", "", "prog-thursday");
      tprog_add_item("PISCES: A Programmable, Protocol-Independent Software Switch", "http://dx.doi.org/10.1145/2934872.2934886", "Muhammad Shahbaz (Princeton University), Sean Choi (Stanford University), Ben Pfaff (VMware), Changhoon Kim (Barefoot Networks), Nick Feamster (Princeton University), Nick McKeown (Stanford University), Jennifer Rexford (Princeton University)", "", "", "", "prog-thursday");
      tprog_add_item("Dataplane Specialization for High-performance OpenFlow Software Switching", "http://dx.doi.org/10.1145/2934872.2934887", "L&aacute;szl&oacute; Moln&aacute;r (Ericsson Research, Hungary), Gergely Pongr&aacute;cz (Ericsson Research, Hungary), G&aacute;bor Enyedi (Ericsson Research, Hungary), Zolt&aacute;n Kis (Ericsson Research, Hungary), Levente Csikor (Budapest University of Technology and Economics), Ferenc Juh&aacute;sz (Budapest University of Technology and Economics), Attila K&ouml;r&ouml;si (Budapest University of Technology and Economics), G&aacute;bor R&eacute;tv&aacute;ri (Budapest University of Technology and Economics)", "", "", "", "prog-thursday");
      tprog_add_session("5:00pm - 5:50pm", "Best of CCR", "", "", "prog-thursday");
      tprog_add_item("CrowdSurf: Empowering Transparency in the Web", "http://dx.doi.org/10.1145/2831347.2831349", "H. Metwalley (Politecnico di Torino), S. Traverso (Politecnico di Torino), M. Mellia (Politecnico di Torino), S. Miskovic (Symantec Corp.), M. Baldi (Politecnico di Torino)", "", "", "", "prog-thursday");
      tprog_add_item("Values and Networks: Steps Toward Exploring their Relationships", "http://dx.doi.org/10.1145/2935634.2935640", "Carsten Orwat (Karlsruhe Institute of Technology), Roland Bless (Karlsruhe Institute of Technology)", "", "", "", "prog-thursday");
      tprog_add_session("5:50pm - 6:20pm", "Closing", "", "", "prog-thursday", true);
?>
    </ul>
  </div>
